[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
render = { path = "../render" }
anyhow = { workspace = true }

# ここに将来:
# game    = { path = "../game" }
# desktop = { path = "../platform/desktop" }
# web     = { path = "../platform/web" }
