[package]
name = "render"
version = "0.1.0"
edition = "2024"

[dependencies]
winit    = { workspace = true }
wgpu     = { workspace = true }
anyhow   = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
